version: "3.7"
services:
  graphql_api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./day17_mini-proj/:/node/
    ports:
      - 3000:3000

  MYDB:
    image: mysql:8.0.32
    ports:
      - 3333:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DBPASSWD}
      MYSQL_DATABASE: ${DBDATABASE}
      MYSQL_USER: ${DBUSER}
      MYSQL_PASSWORD: ${DBPASSWD}
    volumes:
      - ./mydb_volumes:/var/lib/mysql
